default_stages: [pre-commit]
repos:
  - repo: local
    hooks:
      - id: lint-checks
        name: lint-checks
        entry: bash -c "uv run poe lint"
        always_run: true
        pass_filenames: false
        require_serial: true
        language: system
        types: [text]